// Practical example: Simple Windows application using generated import libraries
// This demonstrates real-world usage of the def2lib tool

#include <stdio.h>

#ifdef _WIN32
// Use our generated kernel32.lib for these Windows API functions
extern __declspec(dllimport) unsigned long __stdcall GetTickCount(void);
extern __declspec(dllimport) void __stdcall Sleep(unsigned long dwMilliseconds);
extern __declspec(dllimport) unsigned long __stdcall GetLastError(void);
extern __declspec(dllimport) void __stdcall SetLastError(unsigned long dwErrCode);

// Use our generated user32.lib for UI functions
extern __declspec(dllimport) int __stdcall MessageBoxA(void* hWnd, const char* lpText, const char* lpCaption, unsigned int uType);
extern __declspec(dllimport) int __stdcall GetSystemMetrics(int nIndex);
#endif

// Use our generated msvcrt.lib for C runtime
extern int printf(const char* format, ...);
extern void* malloc(size_t size);
extern void free(void* ptr);
extern char* strcpy(char* dest, const char* src);
extern int strlen(const char* str);

int main() {
    printf("=== Practical Import Library Demo ===\n\n");
    
    // Test 1: Memory management with C runtime
    printf("1. Testing C runtime memory functions:\n");
    char* buffer = (char*)malloc(256);
    if (buffer) {
        strcpy(buffer, "Hello from generated msvcrt.lib!");
        printf("   Allocated and wrote: %s\n", buffer);
        printf("   String length: %d\n", strlen(buffer));
        free(buffer);
        printf("   ✅ Memory operations successful\n");
    } else {
        printf("   ❌ Memory allocation failed\n");
    }
    
#ifdef _WIN32
    // Test 2: Windows system information
    printf("\n2. Testing Windows API functions:\n");
    
    // Get screen dimensions using user32 functions
    int screen_width = GetSystemMetrics(0);  // SM_CXSCREEN
    int screen_height = GetSystemMetrics(1); // SM_CYSCREEN
    printf("   Screen resolution: %dx%d\n", screen_width, screen_height);
    
    // Timing functions using kernel32
    unsigned long start_time = GetTickCount();
    printf("   System uptime: %lu ms\n", start_time);
    
    // Test error handling
    SetLastError(12345);
    unsigned long error = GetLastError();
    printf("   Error code test: %lu\n", error);
    
    printf("   ✅ Windows API functions successful\n");
    
    // Optional: Show message box (uncomment to test)
    /*
    int result = MessageBoxA(NULL, 
        "This message box was shown using an import library generated by def2lib!\n\n"
        "The library was created from a .def file and contains real COFF import objects.",
        "def2lib Success Demo", 0);
    printf("   MessageBox result: %d\n", result);
    */
#endif
    
    printf("\n=== Demo completed successfully! ===\n");
    printf("\nThis demonstrates that the generated import libraries:\n");
    printf("  ✅ Have correct COFF format\n");
    printf("  ✅ Are recognized by linkers\n");
    printf("  ✅ Support both stdcall (Windows API) and cdecl (C runtime) conventions\n");
    printf("  ✅ Handle symbol decoration correctly\n");
    printf("  ✅ Work with real-world Windows development\n");
    
    return 0;
}
